In [1]:
import pandas as pd

In [2]:
resources_df = pd.read_csv('/Users/zeinab/Documents/MSR_internship/manuscript/nature_communications/rebuttal/resources_different_k.csv')

In [3]:
resources_df

,date,id,model_name,data,AR,ood,variable_con,con_percent,lr,weight_decay,batch_size,latent_dim,alpha,num_epoch,seed,atlas_count,training_time,peak_mem_gb
0,20260505,bloodbase-0atlas-ART-lr5e-05-wd5e-05-bs4096-ld...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,0,347.333696,1.076622
1,20260505,bloodbase-1atlas-ART-lr5e-05-wd5e-05-bs4096-ld...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,1,348.132296,1.071720
2,20260505,bloodbase-10atlas-ART-lr5e-05-wd5e-05-bs4096-l...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,10,350.606514,1.071720
3,20260505,bloodbase-100atlas-ART-lr5e-05-wd5e-05-bs4096-...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,100,342.887977,1.071720
4,20260505,bloodbase-1000atlas-ART-lr5e-05-wd5e-05-bs4096...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,1000,340.333302,1.066817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,20260507,bloodbase-10atlas-ARF-lr5e-05-wd5e-05-bs4096-l...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,10,285.490328,1.193926
276,20260507,bloodbase-100atlas-ARF-lr5e-05-wd5e-05-bs4096-...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,100,277.831532,1.193926
277,20260507,bloodbase-1000atlas-ARF-lr5e-05-wd5e-05-bs4096...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,1000,276.586643,1.203914
278,20260507,bloodbase-10000atlas-ARF-lr5e-05-wd5e-05-bs409...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,10000,269.199521,1.203914
279,20260507,bloodbase-50000atlas-ARF-lr5e-05-wd5e-05-bs409...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,50000,280.571972,1.203914

In [4]:
# drop date column
resources_df = resources_df.drop(columns=['date'])
resources_df

,id,model_name,data,AR,ood,variable_con,con_percent,lr,weight_decay,batch_size,latent_dim,alpha,num_epoch,seed,atlas_count,training_time,peak_mem_gb
0,bloodbase-0atlas-ART-lr5e-05-wd5e-05-bs4096-ld...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,0,347.333696,1.076622
1,bloodbase-1atlas-ART-lr5e-05-wd5e-05-bs4096-ld...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,1,348.132296,1.071720
2,bloodbase-10atlas-ART-lr5e-05-wd5e-05-bs4096-l...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,10,350.606514,1.071720
3,bloodbase-100atlas-ART-lr5e-05-wd5e-05-bs4096-...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,100,342.887977,1.071720
4,bloodbase-1000atlas-ART-lr5e-05-wd5e-05-bs4096...,scvi,sctab,True,True,False,1.0,0.00005,0.00005,4096,64,0.0001,150,50,1000,340.333302,1.066817
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,bloodbase-10atlas-ARF-lr5e-05-wd5e-05-bs4096-l...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,10,285.490328,1.193926
276,bloodbase-100atlas-ARF-lr5e-05-wd5e-05-bs4096-...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,100,277.831532,1.193926
277,bloodbase-1000atlas-ARF-lr5e-05-wd5e-05-bs4096...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,1000,276.586643,1.203914
278,bloodbase-10000atlas-ARF-lr5e-05-wd5e-05-bs409...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,10000,269.199521,1.203914
279,bloodbase-50000atlas-ARF-lr5e-05-wd5e-05-bs409...,scvi,sctab,False,True,False,1.0,0.00005,0.00005,4096,128,0.0001,300,90,50000,280.571972,1.203914

In [ ]:
# Define the columns that uniquely identify a configuration (excluding 'AR', 'training_time', 'peak_mem_gb')
group_cols = [
    'model_name', 'ood', 'variable_con', 'con_percent', 'lr', 'weight_decay',
    'batch_size', 'latent_dim', 'alpha', 'num_epoch', 'seed', 'atlas_count'
]

AR_True_df = resources_df[resources_df['AR'] == True]

records = []

for index, row in AR_True_df.iterrows():
    AR_False_row = resources_df[resources_df['AR'] == False]
    for col in group_cols:
        AR_False_row = AR_False_row[AR_False_row[col] == row[col]]

    if AR_False_row.empty:
        raise ValueError(f"No row found for AR False: {row}")
    if len(AR_False_row) > 1:
        raise ValueError(f"More than one row found for AR False: {AR_False_row}")

    false_time = float(AR_False_row['training_time'].values[0])
    false_mem  = float(AR_False_row['peak_mem_gb'].values[0])
    true_time  = float(row['training_time'])
    true_mem   = float(row['peak_mem_gb'])

    diff_time = true_time - false_time
    diff_mem  = true_mem  - false_mem

    records.append({
        'num_epoch':       int(row['num_epoch']),
        'latent_dim':      int(row['latent_dim']),
        'diff_time':       diff_time,
        'diff_mem':        diff_mem,
        'pct_time':        diff_time / false_time * 100,
        'pct_mem':         diff_mem  / false_mem  * 100,
    })

results_df = pd.DataFrame(records)

# keep lists for backwards compatibility
AR_added_time     = results_df['diff_time'].tolist()
AR_added_mem      = results_df['diff_mem'].tolist()
AR_added_time_pct = results_df['pct_time'].tolist()
AR_added_mem_pct  = results_df['pct_mem'].tolist()

In [ ]:
import numpy as np

def print_stats(label, diff_col, pct_col, unit='s', scale=1):
    print(f"\n--- {label} ---")
    print(f"  Mean absolute : {diff_col.mean()*scale:.2f} {unit}   ({diff_col.mean()/60:.2f} min)" if unit == 's' else
          f"  Mean absolute : {diff_col.mean()*scale:.2f} {unit}")
    print(f"  Median absolute: {diff_col.median()*scale:.2f} {unit}")
    print(f"  Mean %         : {pct_col.mean():.1f}%")
    print(f"  Median %       : {pct_col.median():.1f}%")
    print(f"  Std %          : {pct_col.std():.1f}%")

# ── Overall ──────────────────────────────────────────────────────────────────
print("=" * 60)
print("OVERALL (all epochs & latent dims)")
print("=" * 60)
print_stats("Training Time (AR - Standard)", results_df['diff_time'], results_df['pct_time'], unit='s')
print_stats("Peak Memory   (AR - Standard)", results_df['diff_mem'],  results_df['pct_mem'],  unit='GB')

# ── By num_epoch ─────────────────────────────────────────────────────────────
print("\n" + "=" * 60)
print("BREAKDOWN BY num_epoch")
print("=" * 60)
for epoch, grp in results_df.groupby('num_epoch'):
    print(f"\n  num_epoch = {epoch}  (n={len(grp)} pairs)")
    print(f"    Training time  — mean: {grp['diff_time'].mean():.1f} s  "
          f"({grp['diff_time'].mean()/60:.2f} min),  "
          f"mean %: {grp['pct_time'].mean():.1f}%,  "
          f"median %: {grp['pct_time'].median():.1f}%")
    print(f"    Peak memory    — mean: {grp['diff_mem'].mean()*1024:.1f} MB,  "
          f"mean %: {grp['pct_mem'].mean():.1f}%,  "
          f"median %: {grp['pct_mem'].median():.1f}%")